# Generated by Django 5.2.4 on 2025-08-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_form_delete_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_form',
            options={'verbose_name_plural': 'Contact_Form'},
        ),
        migrations.AlterModelTable(
            name='contact_form',
            table='Contact_Form',
        ),
    ]
